/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class familia_java_util_CMT19937 */

#ifndef _Included_familia_java_util_CMT19937
#define _Included_familia_java_util_CMT19937
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     familia_java_util_CMT19937
 * Method:    setSeed
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_familia_java_util_CMT19937_setSeed
  (JNIEnv *, jobject, jlong);

/*
 * Class:     familia_java_util_CMT19937
 * Method:    nextDouble
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_familia_java_util_CMT19937_nextDouble
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
