// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/config.proto

package familia;

public final class Config {
  private Config() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code familia.ModelType}
   *
   * <pre>
   * 模型类型
   * </pre>
   */
  public enum ModelType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>LDA = 0;</code>
     *
     * <pre>
     * Latent Dirichlet Allocation
     * </pre>
     */
    LDA(0, 0),
    /**
     * <code>SLDA = 1;</code>
     *
     * <pre>
     * Sentence-LDA
     * </pre>
     */
    SLDA(1, 1),
    ;

    /**
     * <code>LDA = 0;</code>
     *
     * <pre>
     * Latent Dirichlet Allocation
     * </pre>
     */
    public static final int LDA_VALUE = 0;
    /**
     * <code>SLDA = 1;</code>
     *
     * <pre>
     * Sentence-LDA
     * </pre>
     */
    public static final int SLDA_VALUE = 1;


    public final int getNumber() { return value; }

    public static ModelType valueOf(int value) {
      switch (value) {
        case 0: return LDA;
        case 1: return SLDA;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ModelType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<ModelType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ModelType>() {
            public ModelType findValueByNumber(int number) {
              return ModelType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return familia.Config.getDescriptor().getEnumTypes().get(0);
    }

    private static final ModelType[] VALUES = values();

    public static ModelType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private ModelType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:familia.ModelType)
  }

  public interface ModelConfigOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional .familia.ModelType type = 1 [default = LDA];
    /**
     * <code>optional .familia.ModelType type = 1 [default = LDA];</code>
     *
     * <pre>
     * 模型类型
     * </pre>
     */
    boolean hasType();
    /**
     * <code>optional .familia.ModelType type = 1 [default = LDA];</code>
     *
     * <pre>
     * 模型类型
     * </pre>
     */
    familia.Config.ModelType getType();

    // optional int32 num_topics = 2 [default = 100];
    /**
     * <code>optional int32 num_topics = 2 [default = 100];</code>
     *
     * <pre>
     * 主题数
     * </pre>
     */
    boolean hasNumTopics();
    /**
     * <code>optional int32 num_topics = 2 [default = 100];</code>
     *
     * <pre>
     * 主题数
     * </pre>
     */
    int getNumTopics();

    // optional float alpha = 3 [default = 0.1];
    /**
     * <code>optional float alpha = 3 [default = 0.1];</code>
     *
     * <pre>
     * 主题模型超参alpha
     * </pre>
     */
    boolean hasAlpha();
    /**
     * <code>optional float alpha = 3 [default = 0.1];</code>
     *
     * <pre>
     * 主题模型超参alpha
     * </pre>
     */
    float getAlpha();

    // optional float beta = 4 [default = 0.01];
    /**
     * <code>optional float beta = 4 [default = 0.01];</code>
     *
     * <pre>
     * 主题模型超参beta
     * </pre>
     */
    boolean hasBeta();
    /**
     * <code>optional float beta = 4 [default = 0.01];</code>
     *
     * <pre>
     * 主题模型超参beta
     * </pre>
     */
    float getBeta();

    // optional string word_topic_file = 6 [default = "word_topic.model"];
    /**
     * <code>optional string word_topic_file = 6 [default = "word_topic.model"];</code>
     *
     * <pre>
     * 主题模型word topic矩阵文件名
     * </pre>
     */
    boolean hasWordTopicFile();
    /**
     * <code>optional string word_topic_file = 6 [default = "word_topic.model"];</code>
     *
     * <pre>
     * 主题模型word topic矩阵文件名
     * </pre>
     */
    java.lang.String getWordTopicFile();
    /**
     * <code>optional string word_topic_file = 6 [default = "word_topic.model"];</code>
     *
     * <pre>
     * 主题模型word topic矩阵文件名
     * </pre>
     */
    com.google.protobuf.ByteString
        getWordTopicFileBytes();

    // optional string vocab_file = 7 [default = "vocab_info.txt"];
    /**
     * <code>optional string vocab_file = 7 [default = "vocab_info.txt"];</code>
     *
     * <pre>
     * 词表文件名
     * </pre>
     */
    boolean hasVocabFile();
    /**
     * <code>optional string vocab_file = 7 [default = "vocab_info.txt"];</code>
     *
     * <pre>
     * 词表文件名
     * </pre>
     */
    java.lang.String getVocabFile();
    /**
     * <code>optional string vocab_file = 7 [default = "vocab_info.txt"];</code>
     *
     * <pre>
     * 词表文件名
     * </pre>
     */
    com.google.protobuf.ByteString
        getVocabFileBytes();

    // optional string twe_model_file = 8 [default = ""];
    /**
     * <code>optional string twe_model_file = 8 [default = ""];</code>
     *
     * <pre>
     * Topical Word Embedding 模型文件
     * </pre>
     */
    boolean hasTweModelFile();
    /**
     * <code>optional string twe_model_file = 8 [default = ""];</code>
     *
     * <pre>
     * Topical Word Embedding 模型文件
     * </pre>
     */
    java.lang.String getTweModelFile();
    /**
     * <code>optional string twe_model_file = 8 [default = ""];</code>
     *
     * <pre>
     * Topical Word Embedding 模型文件
     * </pre>
     */
    com.google.protobuf.ByteString
        getTweModelFileBytes();
  }
  /**
   * Protobuf type {@code familia.ModelConfig}
   */
  public static final class ModelConfig extends
      com.google.protobuf.GeneratedMessage
      implements ModelConfigOrBuilder {
    // Use ModelConfig.newBuilder() to construct.
    private ModelConfig(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ModelConfig(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ModelConfig defaultInstance;
    public static ModelConfig getDefaultInstance() {
      return defaultInstance;
    }

    public ModelConfig getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ModelConfig(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              familia.Config.ModelType value = familia.Config.ModelType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              numTopics_ = input.readInt32();
              break;
            }
            case 29: {
              bitField0_ |= 0x00000004;
              alpha_ = input.readFloat();
              break;
            }
            case 37: {
              bitField0_ |= 0x00000008;
              beta_ = input.readFloat();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000010;
              wordTopicFile_ = input.readBytes();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000020;
              vocabFile_ = input.readBytes();
              break;
            }
            case 66: {
              bitField0_ |= 0x00000040;
              tweModelFile_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return familia.Config.internal_static_familia_ModelConfig_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return familia.Config.internal_static_familia_ModelConfig_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              familia.Config.ModelConfig.class, familia.Config.ModelConfig.Builder.class);
    }

    public static com.google.protobuf.Parser<ModelConfig> PARSER =
        new com.google.protobuf.AbstractParser<ModelConfig>() {
      public ModelConfig parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ModelConfig(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ModelConfig> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional .familia.ModelType type = 1 [default = LDA];
    public static final int TYPE_FIELD_NUMBER = 1;
    private familia.Config.ModelType type_;
    /**
     * <code>optional .familia.ModelType type = 1 [default = LDA];</code>
     *
     * <pre>
     * 模型类型
     * </pre>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .familia.ModelType type = 1 [default = LDA];</code>
     *
     * <pre>
     * 模型类型
     * </pre>
     */
    public familia.Config.ModelType getType() {
      return type_;
    }

    // optional int32 num_topics = 2 [default = 100];
    public static final int NUM_TOPICS_FIELD_NUMBER = 2;
    private int numTopics_;
    /**
     * <code>optional int32 num_topics = 2 [default = 100];</code>
     *
     * <pre>
     * 主题数
     * </pre>
     */
    public boolean hasNumTopics() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 num_topics = 2 [default = 100];</code>
     *
     * <pre>
     * 主题数
     * </pre>
     */
    public int getNumTopics() {
      return numTopics_;
    }

    // optional float alpha = 3 [default = 0.1];
    public static final int ALPHA_FIELD_NUMBER = 3;
    private float alpha_;
    /**
     * <code>optional float alpha = 3 [default = 0.1];</code>
     *
     * <pre>
     * 主题模型超参alpha
     * </pre>
     */
    public boolean hasAlpha() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional float alpha = 3 [default = 0.1];</code>
     *
     * <pre>
     * 主题模型超参alpha
     * </pre>
     */
    public float getAlpha() {
      return alpha_;
    }

    // optional float beta = 4 [default = 0.01];
    public static final int BETA_FIELD_NUMBER = 4;
    private float beta_;
    /**
     * <code>optional float beta = 4 [default = 0.01];</code>
     *
     * <pre>
     * 主题模型超参beta
     * </pre>
     */
    public boolean hasBeta() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional float beta = 4 [default = 0.01];</code>
     *
     * <pre>
     * 主题模型超参beta
     * </pre>
     */
    public float getBeta() {
      return beta_;
    }

    // optional string word_topic_file = 6 [default = "word_topic.model"];
    public static final int WORD_TOPIC_FILE_FIELD_NUMBER = 6;
    private java.lang.Object wordTopicFile_;
    /**
     * <code>optional string word_topic_file = 6 [default = "word_topic.model"];</code>
     *
     * <pre>
     * 主题模型word topic矩阵文件名
     * </pre>
     */
    public boolean hasWordTopicFile() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string word_topic_file = 6 [default = "word_topic.model"];</code>
     *
     * <pre>
     * 主题模型word topic矩阵文件名
     * </pre>
     */
    public java.lang.String getWordTopicFile() {
      java.lang.Object ref = wordTopicFile_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          wordTopicFile_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string word_topic_file = 6 [default = "word_topic.model"];</code>
     *
     * <pre>
     * 主题模型word topic矩阵文件名
     * </pre>
     */
    public com.google.protobuf.ByteString
        getWordTopicFileBytes() {
      java.lang.Object ref = wordTopicFile_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        wordTopicFile_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string vocab_file = 7 [default = "vocab_info.txt"];
    public static final int VOCAB_FILE_FIELD_NUMBER = 7;
    private java.lang.Object vocabFile_;
    /**
     * <code>optional string vocab_file = 7 [default = "vocab_info.txt"];</code>
     *
     * <pre>
     * 词表文件名
     * </pre>
     */
    public boolean hasVocabFile() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string vocab_file = 7 [default = "vocab_info.txt"];</code>
     *
     * <pre>
     * 词表文件名
     * </pre>
     */
    public java.lang.String getVocabFile() {
      java.lang.Object ref = vocabFile_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          vocabFile_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string vocab_file = 7 [default = "vocab_info.txt"];</code>
     *
     * <pre>
     * 词表文件名
     * </pre>
     */
    public com.google.protobuf.ByteString
        getVocabFileBytes() {
      java.lang.Object ref = vocabFile_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        vocabFile_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string twe_model_file = 8 [default = ""];
    public static final int TWE_MODEL_FILE_FIELD_NUMBER = 8;
    private java.lang.Object tweModelFile_;
    /**
     * <code>optional string twe_model_file = 8 [default = ""];</code>
     *
     * <pre>
     * Topical Word Embedding 模型文件
     * </pre>
     */
    public boolean hasTweModelFile() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional string twe_model_file = 8 [default = ""];</code>
     *
     * <pre>
     * Topical Word Embedding 模型文件
     * </pre>
     */
    public java.lang.String getTweModelFile() {
      java.lang.Object ref = tweModelFile_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          tweModelFile_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string twe_model_file = 8 [default = ""];</code>
     *
     * <pre>
     * Topical Word Embedding 模型文件
     * </pre>
     */
    public com.google.protobuf.ByteString
        getTweModelFileBytes() {
      java.lang.Object ref = tweModelFile_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tweModelFile_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      type_ = familia.Config.ModelType.LDA;
      numTopics_ = 100;
      alpha_ = 0.1F;
      beta_ = 0.01F;
      wordTopicFile_ = "word_topic.model";
      vocabFile_ = "vocab_info.txt";
      tweModelFile_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, numTopics_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeFloat(3, alpha_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeFloat(4, beta_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(6, getWordTopicFileBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(7, getVocabFileBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(8, getTweModelFileBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, numTopics_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, alpha_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, beta_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getWordTopicFileBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getVocabFileBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getTweModelFileBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static familia.Config.ModelConfig parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static familia.Config.ModelConfig parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static familia.Config.ModelConfig parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static familia.Config.ModelConfig parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static familia.Config.ModelConfig parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static familia.Config.ModelConfig parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static familia.Config.ModelConfig parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static familia.Config.ModelConfig parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static familia.Config.ModelConfig parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static familia.Config.ModelConfig parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(familia.Config.ModelConfig prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code familia.ModelConfig}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements familia.Config.ModelConfigOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return familia.Config.internal_static_familia_ModelConfig_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return familia.Config.internal_static_familia_ModelConfig_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                familia.Config.ModelConfig.class, familia.Config.ModelConfig.Builder.class);
      }

      // Construct using familia.Config.ModelConfig.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = familia.Config.ModelType.LDA;
        bitField0_ = (bitField0_ & ~0x00000001);
        numTopics_ = 100;
        bitField0_ = (bitField0_ & ~0x00000002);
        alpha_ = 0.1F;
        bitField0_ = (bitField0_ & ~0x00000004);
        beta_ = 0.01F;
        bitField0_ = (bitField0_ & ~0x00000008);
        wordTopicFile_ = "word_topic.model";
        bitField0_ = (bitField0_ & ~0x00000010);
        vocabFile_ = "vocab_info.txt";
        bitField0_ = (bitField0_ & ~0x00000020);
        tweModelFile_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return familia.Config.internal_static_familia_ModelConfig_descriptor;
      }

      public familia.Config.ModelConfig getDefaultInstanceForType() {
        return familia.Config.ModelConfig.getDefaultInstance();
      }

      public familia.Config.ModelConfig build() {
        familia.Config.ModelConfig result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public familia.Config.ModelConfig buildPartial() {
        familia.Config.ModelConfig result = new familia.Config.ModelConfig(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.numTopics_ = numTopics_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.alpha_ = alpha_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.beta_ = beta_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.wordTopicFile_ = wordTopicFile_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.vocabFile_ = vocabFile_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.tweModelFile_ = tweModelFile_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof familia.Config.ModelConfig) {
          return mergeFrom((familia.Config.ModelConfig)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(familia.Config.ModelConfig other) {
        if (other == familia.Config.ModelConfig.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasNumTopics()) {
          setNumTopics(other.getNumTopics());
        }
        if (other.hasAlpha()) {
          setAlpha(other.getAlpha());
        }
        if (other.hasBeta()) {
          setBeta(other.getBeta());
        }
        if (other.hasWordTopicFile()) {
          bitField0_ |= 0x00000010;
          wordTopicFile_ = other.wordTopicFile_;
          onChanged();
        }
        if (other.hasVocabFile()) {
          bitField0_ |= 0x00000020;
          vocabFile_ = other.vocabFile_;
          onChanged();
        }
        if (other.hasTweModelFile()) {
          bitField0_ |= 0x00000040;
          tweModelFile_ = other.tweModelFile_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        familia.Config.ModelConfig parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (familia.Config.ModelConfig) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .familia.ModelType type = 1 [default = LDA];
      private familia.Config.ModelType type_ = familia.Config.ModelType.LDA;
      /**
       * <code>optional .familia.ModelType type = 1 [default = LDA];</code>
       *
       * <pre>
       * 模型类型
       * </pre>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .familia.ModelType type = 1 [default = LDA];</code>
       *
       * <pre>
       * 模型类型
       * </pre>
       */
      public familia.Config.ModelType getType() {
        return type_;
      }
      /**
       * <code>optional .familia.ModelType type = 1 [default = LDA];</code>
       *
       * <pre>
       * 模型类型
       * </pre>
       */
      public Builder setType(familia.Config.ModelType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .familia.ModelType type = 1 [default = LDA];</code>
       *
       * <pre>
       * 模型类型
       * </pre>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = familia.Config.ModelType.LDA;
        onChanged();
        return this;
      }

      // optional int32 num_topics = 2 [default = 100];
      private int numTopics_ = 100;
      /**
       * <code>optional int32 num_topics = 2 [default = 100];</code>
       *
       * <pre>
       * 主题数
       * </pre>
       */
      public boolean hasNumTopics() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 num_topics = 2 [default = 100];</code>
       *
       * <pre>
       * 主题数
       * </pre>
       */
      public int getNumTopics() {
        return numTopics_;
      }
      /**
       * <code>optional int32 num_topics = 2 [default = 100];</code>
       *
       * <pre>
       * 主题数
       * </pre>
       */
      public Builder setNumTopics(int value) {
        bitField0_ |= 0x00000002;
        numTopics_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 num_topics = 2 [default = 100];</code>
       *
       * <pre>
       * 主题数
       * </pre>
       */
      public Builder clearNumTopics() {
        bitField0_ = (bitField0_ & ~0x00000002);
        numTopics_ = 100;
        onChanged();
        return this;
      }

      // optional float alpha = 3 [default = 0.1];
      private float alpha_ = 0.1F;
      /**
       * <code>optional float alpha = 3 [default = 0.1];</code>
       *
       * <pre>
       * 主题模型超参alpha
       * </pre>
       */
      public boolean hasAlpha() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional float alpha = 3 [default = 0.1];</code>
       *
       * <pre>
       * 主题模型超参alpha
       * </pre>
       */
      public float getAlpha() {
        return alpha_;
      }
      /**
       * <code>optional float alpha = 3 [default = 0.1];</code>
       *
       * <pre>
       * 主题模型超参alpha
       * </pre>
       */
      public Builder setAlpha(float value) {
        bitField0_ |= 0x00000004;
        alpha_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float alpha = 3 [default = 0.1];</code>
       *
       * <pre>
       * 主题模型超参alpha
       * </pre>
       */
      public Builder clearAlpha() {
        bitField0_ = (bitField0_ & ~0x00000004);
        alpha_ = 0.1F;
        onChanged();
        return this;
      }

      // optional float beta = 4 [default = 0.01];
      private float beta_ = 0.01F;
      /**
       * <code>optional float beta = 4 [default = 0.01];</code>
       *
       * <pre>
       * 主题模型超参beta
       * </pre>
       */
      public boolean hasBeta() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional float beta = 4 [default = 0.01];</code>
       *
       * <pre>
       * 主题模型超参beta
       * </pre>
       */
      public float getBeta() {
        return beta_;
      }
      /**
       * <code>optional float beta = 4 [default = 0.01];</code>
       *
       * <pre>
       * 主题模型超参beta
       * </pre>
       */
      public Builder setBeta(float value) {
        bitField0_ |= 0x00000008;
        beta_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float beta = 4 [default = 0.01];</code>
       *
       * <pre>
       * 主题模型超参beta
       * </pre>
       */
      public Builder clearBeta() {
        bitField0_ = (bitField0_ & ~0x00000008);
        beta_ = 0.01F;
        onChanged();
        return this;
      }

      // optional string word_topic_file = 6 [default = "word_topic.model"];
      private java.lang.Object wordTopicFile_ = "word_topic.model";
      /**
       * <code>optional string word_topic_file = 6 [default = "word_topic.model"];</code>
       *
       * <pre>
       * 主题模型word topic矩阵文件名
       * </pre>
       */
      public boolean hasWordTopicFile() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string word_topic_file = 6 [default = "word_topic.model"];</code>
       *
       * <pre>
       * 主题模型word topic矩阵文件名
       * </pre>
       */
      public java.lang.String getWordTopicFile() {
        java.lang.Object ref = wordTopicFile_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          wordTopicFile_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string word_topic_file = 6 [default = "word_topic.model"];</code>
       *
       * <pre>
       * 主题模型word topic矩阵文件名
       * </pre>
       */
      public com.google.protobuf.ByteString
          getWordTopicFileBytes() {
        java.lang.Object ref = wordTopicFile_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          wordTopicFile_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string word_topic_file = 6 [default = "word_topic.model"];</code>
       *
       * <pre>
       * 主题模型word topic矩阵文件名
       * </pre>
       */
      public Builder setWordTopicFile(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        wordTopicFile_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string word_topic_file = 6 [default = "word_topic.model"];</code>
       *
       * <pre>
       * 主题模型word topic矩阵文件名
       * </pre>
       */
      public Builder clearWordTopicFile() {
        bitField0_ = (bitField0_ & ~0x00000010);
        wordTopicFile_ = getDefaultInstance().getWordTopicFile();
        onChanged();
        return this;
      }
      /**
       * <code>optional string word_topic_file = 6 [default = "word_topic.model"];</code>
       *
       * <pre>
       * 主题模型word topic矩阵文件名
       * </pre>
       */
      public Builder setWordTopicFileBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        wordTopicFile_ = value;
        onChanged();
        return this;
      }

      // optional string vocab_file = 7 [default = "vocab_info.txt"];
      private java.lang.Object vocabFile_ = "vocab_info.txt";
      /**
       * <code>optional string vocab_file = 7 [default = "vocab_info.txt"];</code>
       *
       * <pre>
       * 词表文件名
       * </pre>
       */
      public boolean hasVocabFile() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string vocab_file = 7 [default = "vocab_info.txt"];</code>
       *
       * <pre>
       * 词表文件名
       * </pre>
       */
      public java.lang.String getVocabFile() {
        java.lang.Object ref = vocabFile_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          vocabFile_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string vocab_file = 7 [default = "vocab_info.txt"];</code>
       *
       * <pre>
       * 词表文件名
       * </pre>
       */
      public com.google.protobuf.ByteString
          getVocabFileBytes() {
        java.lang.Object ref = vocabFile_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          vocabFile_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string vocab_file = 7 [default = "vocab_info.txt"];</code>
       *
       * <pre>
       * 词表文件名
       * </pre>
       */
      public Builder setVocabFile(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        vocabFile_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string vocab_file = 7 [default = "vocab_info.txt"];</code>
       *
       * <pre>
       * 词表文件名
       * </pre>
       */
      public Builder clearVocabFile() {
        bitField0_ = (bitField0_ & ~0x00000020);
        vocabFile_ = getDefaultInstance().getVocabFile();
        onChanged();
        return this;
      }
      /**
       * <code>optional string vocab_file = 7 [default = "vocab_info.txt"];</code>
       *
       * <pre>
       * 词表文件名
       * </pre>
       */
      public Builder setVocabFileBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        vocabFile_ = value;
        onChanged();
        return this;
      }

      // optional string twe_model_file = 8 [default = ""];
      private java.lang.Object tweModelFile_ = "";
      /**
       * <code>optional string twe_model_file = 8 [default = ""];</code>
       *
       * <pre>
       * Topical Word Embedding 模型文件
       * </pre>
       */
      public boolean hasTweModelFile() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional string twe_model_file = 8 [default = ""];</code>
       *
       * <pre>
       * Topical Word Embedding 模型文件
       * </pre>
       */
      public java.lang.String getTweModelFile() {
        java.lang.Object ref = tweModelFile_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          tweModelFile_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string twe_model_file = 8 [default = ""];</code>
       *
       * <pre>
       * Topical Word Embedding 模型文件
       * </pre>
       */
      public com.google.protobuf.ByteString
          getTweModelFileBytes() {
        java.lang.Object ref = tweModelFile_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tweModelFile_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string twe_model_file = 8 [default = ""];</code>
       *
       * <pre>
       * Topical Word Embedding 模型文件
       * </pre>
       */
      public Builder setTweModelFile(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        tweModelFile_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string twe_model_file = 8 [default = ""];</code>
       *
       * <pre>
       * Topical Word Embedding 模型文件
       * </pre>
       */
      public Builder clearTweModelFile() {
        bitField0_ = (bitField0_ & ~0x00000040);
        tweModelFile_ = getDefaultInstance().getTweModelFile();
        onChanged();
        return this;
      }
      /**
       * <code>optional string twe_model_file = 8 [default = ""];</code>
       *
       * <pre>
       * Topical Word Embedding 模型文件
       * </pre>
       */
      public Builder setTweModelFileBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        tweModelFile_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:familia.ModelConfig)
    }

    static {
      defaultInstance = new ModelConfig(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:familia.ModelConfig)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_familia_ModelConfig_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_familia_ModelConfig_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022proto/config.proto\022\007familia\"\336\001\n\013ModelC" +
      "onfig\022%\n\004type\030\001 \001(\0162\022.familia.ModelType:" +
      "\003LDA\022\027\n\nnum_topics\030\002 \001(\005:\003100\022\022\n\005alpha\030\003" +
      " \001(\002:\0030.1\022\022\n\004beta\030\004 \001(\002:\0040.01\022)\n\017word_to" +
      "pic_file\030\006 \001(\t:\020word_topic.model\022\"\n\nvoca" +
      "b_file\030\007 \001(\t:\016vocab_info.txt\022\030\n\016twe_mode" +
      "l_file\030\010 \001(\t:\000*\036\n\tModelType\022\007\n\003LDA\020\000\022\010\n\004" +
      "SLDA\020\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_familia_ModelConfig_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_familia_ModelConfig_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_familia_ModelConfig_descriptor,
              new java.lang.String[] { "Type", "NumTopics", "Alpha", "Beta", "WordTopicFile", "VocabFile", "TweModelFile", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
